<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-06T02:48:16Z" name="Default suite" finished-at="2023-05-06T02:48:24Z" duration-ms="8137">
    <groups>
    </groups>
    <test started-at="2023-05-06T02:48:16Z" name="Default test" finished-at="2023-05-06T02:48:24Z" duration-ms="8137">
      <class name="com.sevenrmartsupermarket.tests.AdminUsersTest">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.sevenrmartsupermarket.tests.AdminUsersTest@1046d517]" started-at="2023-05-06T02:48:16Z" name="launchBrowser" finished-at="2023-05-06T02:48:21Z" duration-ms="4903" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verifySuccessUserCreationAlert()[pri:0, instance:com.sevenrmartsupermarket.tests.AdminUsersTest@1046d517]" started-at="2023-05-06T02:48:21Z" name="verifySuccessUserCreationAlert" finished-at="2023-05-06T02:48:24Z" duration-ms="2719" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [×
Alert!
User Created Successfully] but found [×
Alert!
User Created Successfully]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [×
Alert!
User Created Successfully] but found [×
Alert!
User Created Successfully]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.sevenrmartsupermarket.tests.AdminUsersTest.verifySuccessUserCreationAlert(AdminUsersTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessUserCreationAlert -->
        <test-method is-config="true" signature="terminateBrowser(org.testng.ITestResult)[pri:0, instance:com.sevenrmartsupermarket.tests.AdminUsersTest@1046d517]" started-at="2023-05-06T02:48:24Z" name="terminateBrowser" finished-at="2023-05-06T02:48:24Z" duration-ms="455" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifySuccessUserCreationAlert status=FAILURE method=AdminUsersTest.verifySuccessUserCreationAlert()[pri:0, instance:com.sevenrmartsupermarket.tests.AdminUsersTest@1046d517] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- com.sevenrmartsupermarket.tests.AdminUsersTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
